#!/bin/bash
# checks all the links on the website
# uses linkcheck: https://github.com/filiph/linkcheck
# and serve: https://www.npmjs.com/package/serve

cd "$(dirname "${BASH_SOURCE[0]}")" || exit

LOCAL_URL="http://localhost:5000"

# rebuild
./build
# serve on local server
serve . &
# capture PID so server can be killed later
SERVER_PID=$!

until curl -s "$LOCAL_URL" 2>/dev/null 1>&2; do
	echo "Waiting for server to be up..."
	sleep 1
done

linkcheck "$@" "$LOCAL_URL"

kill "$SERVER_PID"
