#!/usr/bin/env bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

if [[ ! -f .env ]]; then
	echo 'No .env file found' >&2
	exit 1
fi

commit_message="$*"
if [[ -z "$commit_message" ]]; then
	git --no-pager diff
	git --no-pager diff --staged
	commit_message="$(gum input --prompt='commit message (empty to skip)> ')" || exit $?
fi

if [[ -z "$commit_message" ]]; then
	echo 'Deploying without committing...' >&2
fi

on_laptop() {
	case "$(on_machine)" in
	linux_arch_*)
		return 0
		;;
	esac
	return 1
}

precommit() {
	if on_laptop; then
		make lint && make || return $?
	fi
	true
}

commit() {
	if [[ -z "$commit_message" ]]; then
		echo 'No commit message, skipping commit' >&2
		return 0
	else
		git add -A && git --no-pager diff --staged && git commit -m "$commit_message" && git push
	fi
}

precommit && commit && {
	if on_laptop; then
		# do a manual sync from this ./dist to remote, this prevents having to build again remotely
		make link_personal_notes
		make built_and_stork
		./scripts/sync_with_retry
	else
		# otherwise, if im on my phone or somewhere else, I can just push and let it build remotely
		make sync_personal_notes_to_server
		deploy exobrain
	fi
}
