#!/usr/bin/env bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

commit() {
	if [[ -z "$1" ]]; then
		git commit
	else
		git commit -m "$*"
	fi
}

git add -A && commit "$*" && git push && deploy exobrain
