#!/usr/bin/env bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}/.." || exit $?

# https://sean.fish/d/with-secrets?redirect
with-secrets go run ./scripts/launch_in_editor.go -dir ./src/content "$@" >>/tmp/exobrain-launch-in-editor.log 2>&1
